In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import os, sys
sys.path.append(os.path.abspath('..'))

In [3]:
df = pd.read_csv('../data/raw/new_hampshire_real_estate_2026.csv')

### Structural Audit

In [4]:
df.head()

,type,sub_type,text,listPrice,sqft,stories,beds,baths,baths_full,baths_full_calc,garage
0,single_family,NaN,Welcome to this spacious home offering endless...,565000,3520.0,3.0,4.0,3.0,1.0,2.0,2.0
1,single_family,NaN,Quintessential New Hampshire Living with Lake ...,449000,2203.0,2.0,3.0,2.0,2.0,2.0,2.0
2,single_family,NaN,Motivated Seller! Antique cape on three acres ...,209900,1350.0,NaN,2.0,1.0,1.0,1.0,NaN
3,single_family,NaN,"Meredith, NH 03253--You won't want to miss thi...",569000,3684.0,2.0,3.0,3.0,2.0,2.0,2.0
4,single_family,NaN,"Welcome to 10 Roy Drive, a true gem located in...",749000,3945.0,2.0,4.0,4.0,2.0,2.0,2.0

In [5]:
df.shape

(5009, 11)

In [6]:
df.duplicated().sum()

np.int64(80)

In [7]:
df[df['sqft'] == 885.0]

,type,sub_type,text,listPrice,sqft,stories,beds,baths,baths_full,baths_full_calc,garage
889,condos,condo,Experience the perfect blend of convenience an...,275000,885.0,1.0,2.0,1.0,1.0,1.0,NaN
1787,condos,condo,Experience the perfect blend of convenience an...,275000,885.0,1.0,2.0,1.0,1.0,1.0,NaN
1997,condos,condo,Experience the perfect blend of convenience an...,305000,885.0,1.0,2.0,1.0,1.0,1.0,NaN
3407,condos,condo,Experience the perfect blend of convenience an...,275000,885.0,1.0,2.0,1.0,1.0,1.0,NaN

In [8]:
df = df.drop_duplicates()

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.isna().sum()

type                  0
sub_type           3897
text                 10
listPrice             0
sqft               1039
stories            1271
beds               1103
baths              1124
baths_full         1306
baths_full_calc    1131
garage             2512
dtype: int64

In [11]:
df.nunique()

type                  7
sub_type              2
text               4812
listPrice          1205
sqft               1957
stories               6
beds                 18
baths                16
baths_full           11
baths_full_calc      15
garage               15
dtype: int64

In [12]:
df.head(1)

,type,sub_type,text,listPrice,sqft,stories,beds,baths,baths_full,baths_full_calc,garage
0,single_family,NaN,Welcome to this spacious home offering endless...,565000,3520.0,3.0,4.0,3.0,1.0,2.0,2.0

In [13]:
df['type'].value_counts()

type
single_family    2284
land             1023
condos            645
townhomes         387
mobile            362
multi_family      224
condo               4
Name: count, dtype: int64

In [14]:
df['sub_type'].value_counts()

sub_type
condo        645
townhouse    387
Name: count, dtype: int64

In [15]:
df['stories'].value_counts()

stories
2.0    1948
1.0    1231
3.0     422
4.0      55
5.0       1
6.0       1
Name: count, dtype: int64

In [16]:
df['garage'].value_counts()

garage
2.0      1295
1.0       779
3.0       221
4.0        68
6.0        17
5.0        14
8.0         9
7.0         6
10.0        2
15.0        1
14.0        1
24.0        1
480.0       1
48.0        1
21.0        1
Name: count, dtype: int64

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4929 entries, 0 to 5008
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   type             4929 non-null   object
 1   sub_type         1032 non-null   object
 2   text             4919 non-null   object
 3   listPrice        4929 non-null   int64
 4   sqft             3890 non-null   float64
 5   stories          3658 non-null   float64
 6   beds             3826 non-null   float64
 7   baths            3805 non-null   float64
 8   baths_full       3623 non-null   float64
 9   baths_full_calc  3798 non-null   float64
 10  garage           2417 non-null   float64
dtypes: float64(7), int64(1), object(3)
memory usage: 462.1+ KB

## Split Data

In [18]:
from sklearn.model_selection import train_test_split

X = df.drop(columns=['listPrice'])
y = df['listPrice']

X_train, X_test, y_train, y_test = train_test_split(X, y, shuffle=True, test_size=0.2, random_state=42)

X_train.shape, y_train.shape, X_test.shape, y_test.shape

((3943, 10), (3943,), (986, 10), (986,))

## Numerical Audit inspection

In [19]:
from src.numerical_audit import numerical_audit

In [22]:
numerical_audit(X_train)

,column_name,data_type,missing_count,missing_rate,mean,median,min_val,max_val,skew,outlier_count,outlier_rate
0,sqft,float64,832,21.0,2141.223401,1792.0,240.0,49502.0,12.942105,144,4.63
1,stories,float64,1021,26.0,1.803901,2.0,1.0,6.0,0.603909,40,1.37
2,beds,float64,878,22.0,3.044046,3.0,0.0,27.0,4.110756,37,1.21
3,baths,float64,895,23.0,2.446194,2.0,1.0,17.0,2.568436,124,4.07
4,baths_full,float64,1035,26.0,1.635832,1.0,1.0,10.0,2.876443,101,3.47
5,baths_full_calc,float64,899,23.0,1.989488,2.0,1.0,15.0,3.536649,161,5.29
6,garage,float64,2005,51.0,2.226522,2.0,1.0,480.0,42.641892,101,5.21

In [21]:
# analysis the numerical audit and update the yaml